/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiRuntimeHealthRouteImport } from './routes/api/runtime/health'
import { Route as ApiRuntimeSnapshotRouteImport } from './routes/api/runtime/snapshot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeHealthRoute = ApiRuntimeHealthRouteImport.update({
  id: '/api/runtime/health',
  path: '/api/runtime/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeSnapshotRoute = ApiRuntimeSnapshotRouteImport.update({
  id: '/api/runtime/snapshot',
  path: '/api/runtime/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/manual': typeof ManualRoute
  '/operations': typeof OperationsRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/runtime/health': typeof ApiRuntimeHealthRoute
  '/api/runtime/snapshot': typeof ApiRuntimeSnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/manual': typeof ManualRoute
  '/operations': typeof OperationsRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/runtime/health': typeof ApiRuntimeHealthRoute
  '/api/runtime/snapshot': typeof ApiRuntimeSnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/manual': typeof ManualRoute
  '/operations': typeof OperationsRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/runtime/health': typeof ApiRuntimeHealthRoute
  '/api/runtime/snapshot': typeof ApiRuntimeSnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/manual'
    | '/operations'
    | '/replay'
    | '/settings'
    | '/stats'
    | '/api/public/health'
    | '/api/runtime/health'
    | '/api/runtime/snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/manual'
    | '/operations'
    | '/replay'
    | '/settings'
    | '/stats'
    | '/api/public/health'
    | '/api/runtime/health'
    | '/api/runtime/snapshot'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/manual'
    | '/operations'
    | '/replay'
    | '/settings'
    | '/stats'
    | '/api/public/health'
    | '/api/runtime/health'
    | '/api/runtime/snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ManualRoute: typeof ManualRoute
  OperationsRoute: typeof OperationsRoute
  ReplayRoute: typeof ReplayRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiRuntimeHealthRoute: typeof ApiRuntimeHealthRoute
  ApiRuntimeSnapshotRoute: typeof ApiRuntimeSnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/health': {
      id: '/api/runtime/health'
      path: '/api/runtime/health'
      fullPath: '/api/runtime/health'
      preLoaderRoute: typeof ApiRuntimeHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/snapshot': {
      id: '/api/runtime/snapshot'
      path: '/api/runtime/snapshot'
      fullPath: '/api/runtime/snapshot'
      preLoaderRoute: typeof ApiRuntimeSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ManualRoute: ManualRoute,
  OperationsRoute: OperationsRoute,
  ReplayRoute: ReplayRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiRuntimeHealthRoute: ApiRuntimeHealthRoute,
  ApiRuntimeSnapshotRoute: ApiRuntimeSnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
